[Scia Reto](https://sciareto.org) mind map
> __version__=`1.1`,showJumps=`true`
---

# 해야할 일들
> mmd.emoticon=`tree`


## 앱

## 크롬익스텐션

## 전략

### 앱 먼저 만든다

#### 결제유인

##### AI 문장 해석

##### PC 익스텐션 서비스

###### Language Reactor가 타겟이다

###### 아직 시장은 충분하지 않다

##### 실제로 학습이 의미가 있는 서비스는

#####

###

##
