/**
 * 자막의 한 조각(segment)을 나타내는 인터페이스입니다.
 */
export interface Subtitle {
  /** 자막의 시작 시간 (초 단위 문자열) */
  start: string;
  /** 자막의 지속 시간 (초 단위 문자열) */
  dur: string;
  /** 자막의 텍스트 내용 */
  text: string;
}

/**
 * 자막 트랙 정보를 나타내는 인터페이스입니다.
 */
export interface SubtitleTrack {
  /** 자막 언어 코드 */
  languageCode: string;
  /** 자막 언어 이름 */
  languageName: string;
  /** 자막의 고유 식별자 (vssId) */
  vssId: string;
  /** 자동 생성된 자막인지 여부 */
  isAutoGenerated: boolean;
}

/**
 * 동영상의 상세 정보(제목, 설명)와 전체 자막 목록을 포함하는 인터페이스입니다.
 */
export interface VideoDetails {
  /** 동영상 제목 */
  title: string;
  /** 동영상 설명 */
  description: string;
  /** 동영상의 전체 자막 목록 (lang) */
  subtitles?: Subtitle[];
  /** 동영상의 전체 자막 목록 (lang2) */
  subtitles2?: Subtitle[];
  /** 사용 가능한 자막 트랙 목록 */
  subtitles_list: SubtitleTrack[];
}

/**
 * 지정된 YouTube 동영상의 제목, 설명 및 전체 자막을 가져오는 메인 함수입니다.
 * @param options - videoId, lang, lang2를 포함하는 옵션 객체
 * @returns 동영상 상세 정보와 자막을 포함하는 Promise<VideoDetails>
 */
export function getVideoDetails(options: {
  /** 대상 YouTube 동영상의 고유 ID */
  videoId: string;
  /** 가져올 자막의 언어 코드 (예: 'en', 'ko'). 지정하지 않으면 'en'이 기본값입니다. */
  lang?: string;
  lang2?: string;
}): Promise<VideoDetails>;

/**
 * 지정된 YouTube 동영상의 자막(transcript) 데이터만 빠르게 가져옵니다.
 * @param options - videoId와 lang을 포함하는 옵션 객체
 * @returns 자막(Subtitle) 객체의 배열을 담은 Promise
 */
export function getSubtitles(options: {
  /** 대상 YouTube 동영상의 고유 ID */
  videoId: string;
  /** 가져올 자막의 언어 코드 (예: 'en', 'ko'). 지정하지 않으면 'en'이 기본값입니다. */
  lang?: string;
  lang2?: string;
}): Promise<{ subtitles: Subtitle[], subtitles2?: Subtitle[] }>;
